
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace MyPro
{
	public abstract class _TblMessageArchiveDetails : SqlClientEntity
	{
		public _TblMessageArchiveDetails()
		{
			this.QuerySource = "TblMessageArchiveDetails";
			this.MappingName = "TblMessageArchiveDetails";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TblMessageArchiveDetailsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Details_ID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Details_ID, Details_ID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TblMessageArchiveDetailsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Details_ID
			{
				get
				{
					return new SqlParameter("@Details_ID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Message_Status
			{
				get
				{
					return new SqlParameter("@Message_Status", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter Archive_ID
			{
				get
				{
					return new SqlParameter("@Archive_ID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Details_phone
			{
				get
				{
					return new SqlParameter("@Details_phone", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter Details_Name
			{
				get
				{
					return new SqlParameter("@Details_Name", SqlDbType.NVarChar, 50);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Details_ID = "Details_ID";
            public const string Message_Status = "Message_Status";
            public const string Archive_ID = "Archive_ID";
            public const string Details_phone = "Details_phone";
            public const string Details_Name = "Details_Name";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Details_ID] = _TblMessageArchiveDetails.PropertyNames.Details_ID;
					ht[Message_Status] = _TblMessageArchiveDetails.PropertyNames.Message_Status;
					ht[Archive_ID] = _TblMessageArchiveDetails.PropertyNames.Archive_ID;
					ht[Details_phone] = _TblMessageArchiveDetails.PropertyNames.Details_phone;
					ht[Details_Name] = _TblMessageArchiveDetails.PropertyNames.Details_Name;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Details_ID = "Details_ID";
            public const string Message_Status = "Message_Status";
            public const string Archive_ID = "Archive_ID";
            public const string Details_phone = "Details_phone";
            public const string Details_Name = "Details_Name";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Details_ID] = _TblMessageArchiveDetails.ColumnNames.Details_ID;
					ht[Message_Status] = _TblMessageArchiveDetails.ColumnNames.Message_Status;
					ht[Archive_ID] = _TblMessageArchiveDetails.ColumnNames.Archive_ID;
					ht[Details_phone] = _TblMessageArchiveDetails.ColumnNames.Details_phone;
					ht[Details_Name] = _TblMessageArchiveDetails.ColumnNames.Details_Name;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Details_ID = "s_Details_ID";
            public const string Message_Status = "s_Message_Status";
            public const string Archive_ID = "s_Archive_ID";
            public const string Details_phone = "s_Details_phone";
            public const string Details_Name = "s_Details_Name";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Details_ID
	    {
			get
	        {
				return base.Getint(ColumnNames.Details_ID);
			}
			set
	        {
				base.Setint(ColumnNames.Details_ID, value);
			}
		}

		public virtual string Message_Status
	    {
			get
	        {
				return base.Getstring(ColumnNames.Message_Status);
			}
			set
	        {
				base.Setstring(ColumnNames.Message_Status, value);
			}
		}

		public virtual int Archive_ID
	    {
			get
	        {
				return base.Getint(ColumnNames.Archive_ID);
			}
			set
	        {
				base.Setint(ColumnNames.Archive_ID, value);
			}
		}

		public virtual string Details_phone
	    {
			get
	        {
				return base.Getstring(ColumnNames.Details_phone);
			}
			set
	        {
				base.Setstring(ColumnNames.Details_phone, value);
			}
		}

		public virtual string Details_Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Details_Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Details_Name, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Details_ID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Details_ID) ? string.Empty : base.GetintAsString(ColumnNames.Details_ID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Details_ID);
				else
					this.Details_ID = base.SetintAsString(ColumnNames.Details_ID, value);
			}
		}

		public virtual string s_Message_Status
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Message_Status) ? string.Empty : base.GetstringAsString(ColumnNames.Message_Status);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Message_Status);
				else
					this.Message_Status = base.SetstringAsString(ColumnNames.Message_Status, value);
			}
		}

		public virtual string s_Archive_ID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Archive_ID) ? string.Empty : base.GetintAsString(ColumnNames.Archive_ID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Archive_ID);
				else
					this.Archive_ID = base.SetintAsString(ColumnNames.Archive_ID, value);
			}
		}

		public virtual string s_Details_phone
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Details_phone) ? string.Empty : base.GetstringAsString(ColumnNames.Details_phone);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Details_phone);
				else
					this.Details_phone = base.SetstringAsString(ColumnNames.Details_phone, value);
			}
		}

		public virtual string s_Details_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Details_Name) ? string.Empty : base.GetstringAsString(ColumnNames.Details_Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Details_Name);
				else
					this.Details_Name = base.SetstringAsString(ColumnNames.Details_Name, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Details_ID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Details_ID, Parameters.Details_ID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Message_Status
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Message_Status, Parameters.Message_Status);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Archive_ID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Archive_ID, Parameters.Archive_ID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Details_phone
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Details_phone, Parameters.Details_phone);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Details_Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Details_Name, Parameters.Details_Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Details_ID
		    {
				get
		        {
					if(_Details_ID_W == null)
	        	    {
						_Details_ID_W = TearOff.Details_ID;
					}
					return _Details_ID_W;
				}
			}

			public WhereParameter Message_Status
		    {
				get
		        {
					if(_Message_Status_W == null)
	        	    {
						_Message_Status_W = TearOff.Message_Status;
					}
					return _Message_Status_W;
				}
			}

			public WhereParameter Archive_ID
		    {
				get
		        {
					if(_Archive_ID_W == null)
	        	    {
						_Archive_ID_W = TearOff.Archive_ID;
					}
					return _Archive_ID_W;
				}
			}

			public WhereParameter Details_phone
		    {
				get
		        {
					if(_Details_phone_W == null)
	        	    {
						_Details_phone_W = TearOff.Details_phone;
					}
					return _Details_phone_W;
				}
			}

			public WhereParameter Details_Name
		    {
				get
		        {
					if(_Details_Name_W == null)
	        	    {
						_Details_Name_W = TearOff.Details_Name;
					}
					return _Details_Name_W;
				}
			}

			private WhereParameter _Details_ID_W = null;
			private WhereParameter _Message_Status_W = null;
			private WhereParameter _Archive_ID_W = null;
			private WhereParameter _Details_phone_W = null;
			private WhereParameter _Details_Name_W = null;

			public void WhereClauseReset()
			{
				_Details_ID_W = null;
				_Message_Status_W = null;
				_Archive_ID_W = null;
				_Details_phone_W = null;
				_Details_Name_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Details_ID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Details_ID, Parameters.Details_ID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Message_Status
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Message_Status, Parameters.Message_Status);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Archive_ID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Archive_ID, Parameters.Archive_ID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Details_phone
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Details_phone, Parameters.Details_phone);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Details_Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Details_Name, Parameters.Details_Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Details_ID
		    {
				get
		        {
					if(_Details_ID_W == null)
	        	    {
						_Details_ID_W = TearOff.Details_ID;
					}
					return _Details_ID_W;
				}
			}

			public AggregateParameter Message_Status
		    {
				get
		        {
					if(_Message_Status_W == null)
	        	    {
						_Message_Status_W = TearOff.Message_Status;
					}
					return _Message_Status_W;
				}
			}

			public AggregateParameter Archive_ID
		    {
				get
		        {
					if(_Archive_ID_W == null)
	        	    {
						_Archive_ID_W = TearOff.Archive_ID;
					}
					return _Archive_ID_W;
				}
			}

			public AggregateParameter Details_phone
		    {
				get
		        {
					if(_Details_phone_W == null)
	        	    {
						_Details_phone_W = TearOff.Details_phone;
					}
					return _Details_phone_W;
				}
			}

			public AggregateParameter Details_Name
		    {
				get
		        {
					if(_Details_Name_W == null)
	        	    {
						_Details_Name_W = TearOff.Details_Name;
					}
					return _Details_Name_W;
				}
			}

			private AggregateParameter _Details_ID_W = null;
			private AggregateParameter _Message_Status_W = null;
			private AggregateParameter _Archive_ID_W = null;
			private AggregateParameter _Details_phone_W = null;
			private AggregateParameter _Details_Name_W = null;

			public void AggregateClauseReset()
			{
				_Details_ID_W = null;
				_Message_Status_W = null;
				_Archive_ID_W = null;
				_Details_phone_W = null;
				_Details_Name_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TblMessageArchiveDetailsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Details_ID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TblMessageArchiveDetailsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TblMessageArchiveDetailsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Details_ID);
			p.SourceColumn = ColumnNames.Details_ID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Details_ID);
			p.SourceColumn = ColumnNames.Details_ID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Message_Status);
			p.SourceColumn = ColumnNames.Message_Status;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Archive_ID);
			p.SourceColumn = ColumnNames.Archive_ID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Details_phone);
			p.SourceColumn = ColumnNames.Details_phone;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Details_Name);
			p.SourceColumn = ColumnNames.Details_Name;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
